In [1]:
import tenserflow as tf
from tenserflow import keras
from tenserflow.keras.preprocessing.text import Tokenizer

ModuleNotFoundError: ignored

In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
!pip uninstall tensorflow

Found existing installation: tensorflow 2.12.0
Uninstalling tensorflow-2.12.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.10/dist-packages/tensorflow-2.12.0.dist-info/*
    /usr/local/lib/python3.10/dist-packages/tensorflow/*
Proceed (Y/n)? Y
Y
  Successfully uninstalled tensorflow-2.12.0


In [4]:
!pip install tensorflow==2.0.0-beta1


ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0-beta1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0)
ERROR: No matching distribution found for tensorflow==2.0.0-beta1


In [5]:
!pip install tensorflow==2.0.0

ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.14.0rc0)
ERROR: No matching distribution found for tensorflow==2.0.0


In [6]:
!pip install tenserflow

ERROR: Could not find a version that satisfies the requirement tenserflow (from versions: none)
ERROR: No matching distribution found for tenserflow


In [7]:


pip 9.0.1 from d:\web\anaconda\lib\site-packages

ERROR: unknown command "9.0.1"


In [8]:
!pip install tenserflow-contrib-python

ERROR: Could not find a version that satisfies the requirement tenserflow-contrib-python (from versions: none)
ERROR: No matching distribution found for tenserflow-contrib-python


In [9]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [34]:
import tensorflow as tf

In [35]:
from tensorflow import keras

In [36]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [37]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [38]:
sentences=[
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?',
]

In [39]:
tokenizer= Tokenizer(num_words=100,oov_token="<00V>")

In [40]:
tokenizer.fit_on_texts(sentences)

In [41]:
word_index=tokenizer.word_index

In [42]:
sequences= tokenizer.texts_to_sequences(sentences)

In [50]:
padded= pad_sequences(sequences, padding='post')

In [44]:
test_data=[
    'I really love my dog',
    'my dog loves my manatee'
    ]

In [45]:
test_seq=tokenizer.texts_to_sequences(test_data)
print('test-seq',test_seq)

test-seq [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]


In [46]:
print(word_index)

{'<00V>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}


In [47]:
print(sequences)

[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


In [51]:
print(padded)

[[ 5  3  2  4  0  0  0]
 [ 5  3  2  7  0  0  0]
 [ 6  3  2  4  0  0  0]
 [ 8  6  9  2  4 10 11]]


In [52]:
#the longest sentence has 7 words so the padding of '0' happens for the shorter sentences
#'post' helps in keeping the padding after the word indexes